
# --- Excavator Durability Settings ---
DurabilityWoodenExcavator=302 #Durability of the Wooden Excavator | default: 302
DurabilityStoneExcavator=650 #Durability of the Stone Excavator | default: 650
DurabilityIronExcavator=1000 #Durability of the Iron Excavator | default: 1300
DurabilityGoldExcavator=550 #Durability of the Gold Excavator | default: 750
DurabilityLapisExcavator=880 #Durability of the Lapis Excavator | default: 1100
DurabilityRedstoneExcavator=800 #Durability of the Redstone Excavator | default: 1100
DurabilityObsidianExcavator=11200 #Durability of the Obsidian Excavator | default: 11200
DurabilityDiamondExcavator=8025 #Durability of the Diamond Excavator | default: 8025
DurabilityEmeraldExcavator=9068 #Durability of the Emerald Excavator | default: 9768
DurabilityNetheriteExcavator=13675 #Durability of the Netherite Excavator | default: 13675

# --- Excavator Radius Settings ---
RadiusWoodenExcavator=1 #Excavation radius for Wooden Excavator (radius 1 = 3×1 area) | default: 1
RadiusStoneExcavator=1 #Excavation radius for Stone Excavator (radius 1 = 3×1 area) | default: 1
RadiusIronExcavator=1 #Excavation radius for Iron Excavator (radius 1 = 3×1 area) | default: 1
RadiusGoldExcavator=2 #Excavation radius for Gold Excavator (radius 1 = 3×1 area) | default: 1
RadiusLapisExcavator=1 #Excavation radius for Lapis Excavator (radius 1 = 3×1 area) | default: 1
RadiusRedstoneExcavator=1 #Excavation radius for Redstone Excavator (radius 1 = 3×1 area) | default: 1
RadiusObsidianExcavator=2 #Excavation radius for Obsidian Excavator (radius 1 = 3×1 area) | default: 1
RadiusDiamondExcavator=3 #Excavation radius for Diamond Excavator (radius 1 = 3×1 area) | default: 1
RadiusEmeraldExcavator=3 #Excavation radius for Emerald Excavator (radius 1 = 3×1 area) | default: 1
RadiusNetheriteExcavator=4 #Excavation radius for Netherite Excavator (radius 1 = 3×1 area) | default: 1

