#General mod settings
[general]
	#Blur is used to prevent nasty aliasing/flicker artifacts at the cost of clarity
	#Range: 0 ~ 2
	dynamicGuiBlurLevel = 1
	#Enables or disables idle visual in the server player list tab screen
	showIdleStatesInPlayerList = true
	#Disables the background rendering for most guis, might hide things like JEI or other things count as background rendering
	dynamicGuiDisableBackgroundRendering = true
	#Plays a sutble sound when a player clicks their mouse in a Gui
	playMouseClickSounds = true
	#Plays a sound when a player opens some Guis
	playScreenOpenSounds = true
	#Enables or disables the non typing animations used when showing the open Gui, such as head looking, arms moving up, arms pointing and clicking
	showPlayerAnimation_Gui = true
	#Show the chat typing Gui in world
	showPlayerActiveChatGui = true
	#Adjust the size of the circle used to cut off extra info beyond their main area of their gui, visual issues may occur of too big. Set to -1 to disable
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	dynamicGuiSizeRadiusInPixelsToShow = 112.0
	#Enables or disables idle animation
	showPlayerAnimation_Idle = true
	#How close another player has to be to another player to see what they're doing in GUI, item transferring, mouse movement, etc
	#Range: > 0
	distanceRequiredToShowGUIInfo = 10
	#SETTING THESE SERVER SIDE SETTINGS TO FALSE WILL OVERRIDE ANY OF THE SAME CLIENT SETTINGS THAT ARE SET TO TRUE (for all clients)
	dummySetting = true
	#Show any Gui they're using that isn't chat typing related in world
	showPlayerActiveNonChatGui = true
	#Delay in ticks before sending a new image of a gui to other clients, 10 = twice a second, 0 = no delay, 20 = once a second, more frequent might affect performance and network load
	#Range: > 5
	dynamicGuiTickSendRateOfGUIUpdates = 10
	#If enabled, only sends the initial image of a players gui, does not constantly update after it's been opened.
	dynamicGuiDontSendConstantGUIUpdates = false
	#Show a clients entire screen instead of using dynamicGuiSizeRadiusInPixelsToShow for a circle fade in a 512x512 area, WARNING: experimental, has cpu and network performance impact. Tweak dynamicGuiSizeRadiusInPixelsToShow to -1 or something large if you use this setting.
	dynamicGuiShowClientsEntireScreen = false
	#Enables or disables idle visual above player head
	showIdleStatesInPlayerAboveHead = true
	#Setting false disables all animations
	showPlayerAnimations = true
	#Disable new dynamic gui system and use old simple visual.
	dynamicGuiUseOldSimpleGUIVisual = false
	#Show items being transferred between player and container
	showItemsBeingTransferredBetweenPlayerAndContainer = true
	#Enables or disables typing animation
	showPlayerAnimation_Typing = true
	#Show 'Player is typing...' on the chat screen
	screenTypingVisible = true
